name: Custom Issue
description: Customisable issue report
title: "Issue: "
body:
  - type: textarea
    id: custom-description
    attributes:
      label: Description
      description: A clear and detailed description of the issue.
      placeholder: Please provide a detailed and specific description of your issue or suggestion, including any relevant context or steps to reproduce.
    validations:
      required: true