name: Custom Issue
description: Customisable issue report
title: "Custom: "
body:
  - type: textarea
    id: custom-description
    attributes:
      label: Description
      description: A clear and detailed description of the issue.
      placeholder: Please describe your issue or suggestion in detail. Be as contained and specific as possible.
    validations:
      required: true