function test_pass = kWaveArray_rotated_point_sources_2D(plot_comparisons, plot_simulations)
% DESCRIPTION:
%       Unit test to compare the acoustic fields generated by on-grid point
%       sources with fields from a rotated array of off-grid point sources
%       created using the kWaveArray class.
%
% ABOUT:
%       author      - Bradley TReeby
%       date        - 26th February 2025
%       last update - 26th February 2025
%       
% This function is part of the k-Wave Toolbox (http://www.k-wave.org)
% Copyright (C) 2025- Bradley Treeby

% This file is part of k-Wave. k-Wave is free software: you can
% redistribute it and/or modify it under the terms of the GNU Lesser
% General Public License as published by the Free Software Foundation,
% either version 3 of the License, or (at your option) any later version.
% 
% k-Wave is distributed in the hope that it will be useful, but WITHOUT ANY
% WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
% FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
% more details. 
% 
% You should have received a copy of the GNU Lesser General Public License
% along with k-Wave. If not, see <http://www.gnu.org/licenses/>.

% check for plot inputs, and set to true if nargin is zero (to allow the
% test to be run independent of runUnitTests)
if nargin == 0
    plot_comparisons = true;
    plot_simulations = true;
end

% set pass variable
test_pass = true;

% set comparison threshold
comparison_thresh = 5;  % 5% error threshold

% =========================================================================
% DEFINE GRID PROPERTIES
% =========================================================================

% grid properties
Nx = 127;
Ny = 127;
dx = 1e-3;
kgrid = kWaveGrid(Nx, dx, Ny, dx);

% medium properties
c0 = 1500;  % [m/s]
medium.sound_speed = c0;

% time array
kgrid.makeTime(c0, 0.3);

% define source parameters
source_grid_pos = 40:50;
num_source_points = length(source_grid_pos);
source_freq = 200e3;  % [Hz]
rotation_angle = 45;  % [degrees]

% define spatially varying source amplitudes and phases
amp = linspace(0.1, 2, num_source_points);
phase = linspace(0, pi, num_source_points);

% create source signals with varying amplitude and phase
source_signals = createCWSignals(kgrid.t_array, source_freq, amp, phase);

% define sensor to capture final pressure field
sensor.record = {'p_final'};

% =========================================================================
% SIMULATION WITH ON-GRID SOURCES
% =========================================================================

% define on-grid source mask with points along a line
source.p_mask = zeros(Nx, Ny);
source.p_mask(ceil(Nx/2), source_grid_pos) = 1;

% assign source signals to each source point
source.p = source_signals;

% run k-Wave simulation with on-grid sources
sensor_data = kspaceFirstOrder2D(kgrid, medium, source, sensor, 'PlotSim', plot_simulations);

% =========================================================================
% SIMULATION WITH ROTATED OFF-GRID SOURCES
% =========================================================================

% create empty kWaveArray
karray = kWaveArray();

% add custom point elements at same locations as on-grid sources
element_dim = 1;
measure = kgrid.dx.^element_dim;
for ind = 1:num_source_points
    y_pos = kgrid.y_vec(source_grid_pos(ind));
    karray.addCustomElement([kgrid.x_vec(ceil(Nx/2)); y_pos], measure, element_dim, ['point ' num2str(ind)]);
end

% apply rotation to the array
translation = [0; 0];  % no translation
karray.setArrayPosition(translation, rotation_angle);

% create source using binary mask from karray
source_off_grid.p_mask = karray.getArrayBinaryMask(kgrid);

% get distributed source signals
source_off_grid.p = karray.getDistributedSourceSignal(kgrid, source_signals);

% run k-Wave simulation with rotated off-grid sources
sensor_data_off_grid = kspaceFirstOrder2D(kgrid, medium, source_off_grid, sensor, 'PlotSim', plot_simulations);

% =========================================================================
% COMPARISON AND ERROR CALCULATION
% =========================================================================

% final pressure fields for comparison
ref = sensor_data.p_final;
rotated = sensor_data_off_grid.p_final;

% rotate the off-grid result back to match orientation of on-grid result
rotated_aligned = imrotate(rotated, -rotation_angle, 'bicubic', 'crop');

% extract central region to avoid boundary effects from rotation
crop_range = 30:97;
ref_cropped = ref(crop_range, crop_range);
rotated_cropped = rotated_aligned(crop_range, crop_range);

% compute error as percentage of maximum value
err = 100 * max(abs(ref_cropped(:) - rotated_cropped(:))) / max(abs(ref_cropped(:)));

% check if error is within threshold
if err > comparison_thresh
    test_pass = false;
end

% =========================================================================
% VISUALISATION
% =========================================================================

% plot pressure fields and error
if plot_comparisons
    
    figure;
    
    subplot(2, 2, 1);
    imagesc(source.p_mask);
    title('On-grid Source Mask');
    axis image;
    colorbar;
    
    subplot(2, 2, 2);
    imagesc(source_off_grid.p_mask);
    title('Off-grid Source Mask (Rotated)');
    axis image;
    colorbar;
    
    subplot(2, 2, 3);
    imagesc(ref_cropped);
    title('On-grid Pressure Field');
    axis image;
    colorbar;
    
    subplot(2, 2, 4);
    imagesc(rotated_cropped);
    title(['Off-grid Pressure Field (Rotated ' num2str(rotation_angle) '°)']);
    axis image;
    colorbar;
    
    figure;
    
    subplot(1, 3, 1);
    imagesc(ref_cropped);
    title('On-grid Result');
    axis image;
    colorbar;
    
    subplot(1, 3, 2);
    imagesc(rotated_cropped);
    title(['Rotated Off-grid Result (Rotated ' num2str(rotation_angle) '°)']);
    axis image;
    colorbar;
    
    subplot(1, 3, 3);
    imagesc(abs(ref_cropped - rotated_cropped));
    title(['Difference (Error: ' num2str(err, '%.2f') '%)']);
    axis image;
    colorbar;
    
end
